### ISSUE TITLE
COVID-19 won't let us continue testing, work paused

### ISSUE THREAD

**Issue by karmanyaahm** [FRCTeam695/Team695RobotCode2020#32]
see title

idk how to solve this issue and who to assign it to

**Comment by JeWangWongWing** [comment]
Thank you for bringing this subtle issue to our attention; it likely would've flown under all of our radars. Thanks, keep up the good work!
![Great job!](https://user-images.githubusercontent.com/55375224/86403697-30dd5680-bc7c-11ea-8d87-f4a215cf48ee.jpg)
